export const coreDefaults = {
  "botMode": "paper",
  "baseQuoteAsset": "USDT",
  "startingCash": 10000,
  "userRegion": "BE",
  "exchangeCapabilitiesEnabled": [],
  "exchangeCapabilitiesDisabled": [],
  "tradingIntervalSeconds": 120,
  "watchlist": [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "ADAUSDT",
    "LINKUSDT",
    "AVAXUSDT",
    "DOGEUSDT",
    "TRXUSDT",
    "LTCUSDT",
    "DOTUSDT",
    "UNIUSDT",
    "AAVEUSDT",
    "NEARUSDT",
    "SUIUSDT",
    "APTUSDT",
    "BCHUSDT"
  ],
  "enableDynamicWatchlist": true,
  "watchlistTopN": 100,
  "watchlistFetchPerPage": 250,
  "dynamicWatchlistMinSymbols": 40,
  "watchlistExcludeStablecoins": true,
  "watchlistExcludeLeveragedTokens": true,
  "watchlistInclude": [],
  "watchlistExclude": [],
  "stpTelemetryLimit": 20,
  "exitOnSpreadShockBps": 20,
  "divergenceMinPaperTrades": 4,
  "divergenceMinLiveTrades": 3,
  "divergenceAlertScore": 0.42,
  "divergenceBlockScore": 0.68,
  "divergenceAlertSlipGapBps": 3.5,
  "gitShortClonePath": "C:\\code\\Codex-ai-trading-bot"
};
