export const marketDataDefaults = {
  "klineInterval": "15m",
  "enableCrossTimeframeConsensus": true,
  "lowerTimeframeInterval": "5m",
  "higherTimeframeInterval": "1h",
  "lowerTimeframeLimit": 120,
  "higherTimeframeLimit": 120,
  "higherTimeframeIntervalDaily": "1d",
  "higherTimeframeLimitDaily": 120,
  "enableDailyTimeframe": true,
  "fundingRateHistoryLimit": 200,
  "enableAggtradeOrderflow": true,
  "aggtradeWindowSeconds": 60,
  "aggtradeBufferSize": 500,
  "enableBtcDominance": true,
  "btcDominanceCacheMinutes": 30,
  "enableVolumeProfile": true,
  "volumeProfileBins": 24,
  "vwapLookbackCandles": 96,
  "enableGlobalMarketContext": true,
  "globalMarketCacheMinutes": 20,
  "crossTimeframeMinAlignmentScore": 0.42,
  "crossTimeframeMaxVolGapPct": 0.03,
  "klineLimit": 180,
  "backtestCandleLimit": 500,
  "historyCacheEnabled": true,
  "historyFetchBatchSize": 1000,
  "historyMaxGapFillRanges": 24,
  "historyPartitionGranularity": "month",
  "historyVerifyFreshnessMultiplier": 4,
  "marketSnapshotCacheMinutes": 4,
  "marketSnapshotConcurrency": 5,
  "marketSnapshotBudgetSymbols": 28,
  "exchangeInfoCacheMs": 21600000,
  "restMarketDataFallbackMinMs": 30000,
  "restBookTickerFallbackMinMs": 60000,
  "restDepthFallbackMinMs": 120000,
  "restTimeframeFallbackMinMs": 60000,
  "requestWeightBackoffMaxMs": 60000,
  "requestWeightWarnThreshold1m": 4800,
  "restHotCallerDepthWeightThreshold": 5000,
  "restHotCallerPrivateTradeWeightThreshold": 2000,
  "newsLookbackHours": 20,
  "newsCacheMinutes": 10,
  "newsHeadlineLimit": 12,
  "announcementLookbackHours": 48,
  "announcementCacheMinutes": 15,
  "marketStructureCacheMinutes": 3,
  "marketStructureLookbackPoints": 12,
  "calendarLookbackDays": 30,
  "calendarCacheMinutes": 30,
  "newsMinSourceQuality": 0.68,
  "newsMinReliabilityScore": 0.64,
  "newsStrictWhitelist": true,
  "sourceReliabilityMinOperationalScore": 0.22,
  "sourceReliabilityMaxRecentFailures": 2,
  "sourceReliabilityRateLimitCooldownMinutes": 30,
  "sourceReliabilityTimeoutCooldownMinutes": 12,
  "sourceReliabilityFailureCooldownMinutes": 8,
  "enableMarketSentimentContext": true,
  "marketSentimentCacheMinutes": 15,
  "alternativeApiBaseUrl": "https://api.alternative.me",
  "coinGeckoApiBaseUrl": "https://api.coingecko.com/api/v3",
  "enableOnChainLiteContext": true,
  "onChainLiteCacheMinutes": 30,
  "onChainLiteStablecoinIds": [
    "tether",
    "usd-coin",
    "dai",
    "first-digital-usd",
    "ethena-usde"
  ],
  "onChainLiteMajorIds": [
    "bitcoin",
    "ethereum",
    "binancecoin",
    "solana",
    "ripple",
    "dogecoin"
  ],
  "onChainLiteTrendingLimit": 7,
  "enableVolatilityContext": true,
  "volatilityCacheMinutes": 20,
  "deribitApiBaseUrl": "https://www.deribit.com/api/v2",
  "enableEventDrivenData": true,
  "enableLocalOrderBook": true,
  "localBookMaxSymbols": 28,
  "publicStreamMaxStreamsPerConnection": 180,
  "publicStreamStartupWaitMs": 3500,
  "publicStreamStaleMs": 90000,
  "publicStreamMonitorIntervalMs": 30000,
  "userStreamStartupWaitMs": 2500,
  "streamTradeBufferSize": 120,
  "streamDepthLevels": 20,
  "streamDepthSnapshotLimit": 200,
  "maxDepthEventAgeMs": 15000,
  "localBookBootstrapWaitMs": 450,
  "localBookWarmupMs": 2500,
  "enableMarketProviderDerivativesContext": true,
  "enableMarketProviderMacroContext": true,
  "enableMarketProviderExecutionFeedback": true,
  "enableMarketProviderCrossExchangeDivergence": true,
  "enableMarketProviderStablecoinFlows": true,
  "enableMarketProviderMicrostructurePriors": true,
  "referenceVenueFetchEnabled": false,
  "referenceVenueQuoteUrls": [],
  "referenceVenueMinQuotes": 2,
  "referenceVenueMaxDivergenceBps": 18
};
