export const serviceDefaults = {
  "releaseChannel": "paper",
  "canaryTradingEnabled": false,
  "canaryMaxTradesPerDay": 1,
  "canaryMaxPositionFraction": 0.02,
  "canaryAllowedSymbols": [],
  "canaryAllowedStrategies": [],
  "trainingMode": false,
  "localOnlyMode": false,
  "exchangeProvider": "binance",
  "accountProfile": "paper",
  "metricsEnabled": false,
  "metricsBindLocalOnly": true,
  "enableCanaryLiveMode": true,
  "canaryLiveTradeCount": 5,
  "canaryLiveSizeMultiplier": 0.35,
  "serviceRestartDelaySeconds": 8,
  "serviceRestartBackoffMultiplier": 1.8,
  "serviceRestartMaxDelaySeconds": 180,
  "serviceStatusFilename": "service-status.json",
  "serviceMaxRestartsPerHour": 20
};
