import { resolveBotPersonalityMode } from "../runtime/botPersonalityMode.js";

const PLAYBOOKS = {
  bull_trend: { allowedStrategyFamilies: ["trend", "breakout", "pullback"], blockedStrategyFamilies: [], maxRiskMultiplier: 1, maxPositionCount: 4, maxPositionFraction: 0.25, minLiquidityScore: 0.55, minDataQuality: 0.65, allowedExecutionStyles: ["maker", "limit"], exitAggressiveness: "normal", neuralInfluenceLimit: 0.35, fastExecutionPermission: "paper_only", requiresOperatorApproval: false },
  bear_trend: { allowedStrategyFamilies: ["mean_reversion", "defensive"], blockedStrategyFamilies: ["aggressive_breakout"], maxRiskMultiplier: 0.45, maxPositionCount: 2, maxPositionFraction: 0.12, minLiquidityScore: 0.7, minDataQuality: 0.75, allowedExecutionStyles: ["maker"], exitAggressiveness: "high", neuralInfluenceLimit: 0.15, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  sideways_range: { allowedStrategyFamilies: ["range", "mean_reversion"], blockedStrategyFamilies: ["momentum_chase"], maxRiskMultiplier: 0.55, maxPositionCount: 3, maxPositionFraction: 0.15, minLiquidityScore: 0.65, minDataQuality: 0.7, allowedExecutionStyles: ["maker", "limit"], exitAggressiveness: "normal", neuralInfluenceLimit: 0.2, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  high_volatility: { allowedStrategyFamilies: ["defensive"], blockedStrategyFamilies: ["fast_breakout", "low_timeframe_scalp"], maxRiskMultiplier: 0.25, maxPositionCount: 1, maxPositionFraction: 0.08, minLiquidityScore: 0.8, minDataQuality: 0.8, allowedExecutionStyles: ["maker"], exitAggressiveness: "very_high", neuralInfluenceLimit: 0.1, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  low_volatility: { allowedStrategyFamilies: ["range", "pullback"], blockedStrategyFamilies: ["volatility_breakout"], maxRiskMultiplier: 0.65, maxPositionCount: 3, maxPositionFraction: 0.15, minLiquidityScore: 0.55, minDataQuality: 0.65, allowedExecutionStyles: ["maker", "limit"], exitAggressiveness: "normal", neuralInfluenceLimit: 0.25, fastExecutionPermission: "paper_only", requiresOperatorApproval: false },
  low_liquidity: { allowedStrategyFamilies: ["defensive"], blockedStrategyFamilies: ["fast_execution", "market_order"], maxRiskMultiplier: 0.15, maxPositionCount: 1, maxPositionFraction: 0.05, minLiquidityScore: 0.85, minDataQuality: 0.8, allowedExecutionStyles: ["maker"], exitAggressiveness: "high", neuralInfluenceLimit: 0.05, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  news_shock: { allowedStrategyFamilies: ["exit_management"], blockedStrategyFamilies: ["all_entries"], maxRiskMultiplier: 0, maxPositionCount: 0, maxPositionFraction: 0, minLiquidityScore: 0.85, minDataQuality: 0.85, allowedExecutionStyles: ["protective_exit"], exitAggressiveness: "very_high", neuralInfluenceLimit: 0, fastExecutionPermission: "disabled", requiresOperatorApproval: true },
  weekend: { allowedStrategyFamilies: ["high_liquidity_only"], blockedStrategyFamilies: ["low_liquidity_alt"], maxRiskMultiplier: 0.35, maxPositionCount: 2, maxPositionFraction: 0.1, minLiquidityScore: 0.75, minDataQuality: 0.75, allowedExecutionStyles: ["maker"], exitAggressiveness: "high", neuralInfluenceLimit: 0.1, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  funding_window: { allowedStrategyFamilies: ["defensive"], blockedStrategyFamilies: ["leverage_sensitive"], maxRiskMultiplier: 0.35, maxPositionCount: 2, maxPositionFraction: 0.1, minLiquidityScore: 0.75, minDataQuality: 0.75, allowedExecutionStyles: ["maker"], exitAggressiveness: "high", neuralInfluenceLimit: 0.1, fastExecutionPermission: "disabled", requiresOperatorApproval: false },
  exchange_degraded: { allowedStrategyFamilies: ["exit_management"], blockedStrategyFamilies: ["all_entries"], maxRiskMultiplier: 0, maxPositionCount: 0, maxPositionFraction: 0, minLiquidityScore: 0.9, minDataQuality: 0.9, allowedExecutionStyles: ["protective_exit"], exitAggressiveness: "very_high", neuralInfluenceLimit: 0, fastExecutionPermission: "disabled", requiresOperatorApproval: true },
  recovery_mode: { ...resolveBotPersonalityMode("recovery_mode"), allowedStrategyFamilies: ["exit_management"], blockedStrategyFamilies: ["all_entries"], maxRiskMultiplier: 0, maxPositionCount: 0, maxPositionFraction: 0, minLiquidityScore: 0.8, minDataQuality: 0.8, allowedExecutionStyles: ["protective_exit"], exitAggressiveness: "very_high", neuralInfluenceLimit: 0, fastExecutionPermission: "disabled", requiresOperatorApproval: true }
};

export function getRegimePlaybook(regime = "sideways_range") {
  const key = `${regime || "sideways_range"}`.trim().toLowerCase();
  return { regime: PLAYBOOKS[key] ? key : "sideways_range", ...(PLAYBOOKS[key] || PLAYBOOKS.sideways_range) };
}
